cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch100.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch101.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch102.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch103.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch104.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch105.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch106.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch107.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch108.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch109.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch110.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch111.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch112.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch113.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch114.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch115.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch116.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch117.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch118.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch119.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch120.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch121.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch122.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch123.npy; sbatch -N 1 -c 1 -p cpu monica.sl
sleep 70m
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch124.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch125.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch126.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch127.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch128.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch129.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch130.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch131.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch132.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch133.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch134.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch135.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch136.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch137.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch138.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch139.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch140.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch141.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch142.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch143.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch144.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch145.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch146.npy; sbatch -N 1 -c 1 -p cpu monica.sl
sleep 70m
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch147.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch148.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch149.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch150.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch151.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch152.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch153.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch154.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch155.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch156.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch157.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch158.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch159.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch160.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch161.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch162.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch163.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch164.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch165.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch166.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch167.npy; sbatch -N 1 -c 1 -p cpu monica.sl
sleep 60m
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch168.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch169.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch170.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch171.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch172.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch173.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch174.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch175.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch176.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch177.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch178.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch179.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch180.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch181.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch182.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch183.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch184.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch185.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch186.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch187.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch188.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch189.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch190.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch191.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch192.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch193.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch194.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch195.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch196.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch197.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch198.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/clay/monica_dirbatch199.npy; sbatch -N 1 -c 1 -p cpu monica.sl
