cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch146.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch147.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch148.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch149.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch150.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch151.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch152.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch153.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch154.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch155.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch156.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch157.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch158.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch159.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch160.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch161.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch162.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch163.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch164.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch165.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch166.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch167.npy; sbatch -N 1 -c 1 -p cpu monica.sl
sleep 60m
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch168.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch169.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch170.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch171.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch172.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch173.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch174.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch175.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch176.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch177.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch178.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch179.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch180.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch181.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch182.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch183.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch184.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch185.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch186.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch187.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch188.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch189.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch190.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch191.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch192.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch193.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch194.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch195.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch196.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch197.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch198.npy; sbatch -N 1 -c 1 -p cpu monica.sl
cd /trinity/home/m.gasanov/monica/parralel/sobol_parralel/bulk_density/monica_dirbatch199.npy; sbatch -N 1 -c 1 -p cpu monica.sl
